version: '3'

services:
  hreact:
    image: node:latest
    container_name: 'sirokuro-dev3'
    hostname: 'sirokuro-dev3'
    ports:
      - '3003:3000'
    stdin_open: true
    tty: true
    working_dir: '/var/www/html'
    volumes:
      - ./src:/var/www/html
    networks:
      - sirokuronet
networks:
  sirokuronet:
    external: true

